### ISSUE TITLE
GitHub 特定文件夹或文件下载工具    报错    “链接不正确，请查看链接是否有效”

### ISSUE THREAD

**Issue by Kiloland** [Momo707577045/github-directory-downloader#1]
谢谢你的效率工具列表！！！很好用
但是现在github指定文件夹下载的功能好像bug了
![image](https://user-images.githubusercontent.com/6738537/137308989-04aa9101-b331-452d-b179-b982ccd4ba08.png)
用测试链接也不能下载.

**Comment by 15921483570** [comment]
同问

**Comment by Momo707577045** [comment]
感谢反馈，我来晚了，问题已修复，试试看还有没有问题？

**Comment by Nana2222** [comment]
出现了同样的问题，之前是可以正常使用的
