### ISSUE TITLE
链接地址可以访问，无法下载

### ISSUE THREAD

**Issue by hellorayza** [Momo707577045/github-directory-downloader#2]
![image](https://user-images.githubusercontent.com/28865896/168005146-abc842f0-d83e-4435-a155-206a5118fcc3.png)

https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache

**Comment by Momo707577045** [comment]
本地测试下载成功，或许是当时 github 网络不稳定，无法正常访问。
换个时间段再试试就 ok 了
