### ISSUE TITLE
功能问题：依然下载了全部项目文件

### ISSUE THREAD

**Issue by crliu95** [Momo707577045/github-directory-downloader#4]
测试目标：在stpackages项目下单独下载csdid2文件夹及内部的所有文件（和子文件夹）
使用路径：https://github.com/friosavila/stpackages/tree/main/csdid2
下载结果：一个名为“stpackages_main_.zip”的压缩包，里面包括了除csdid2之外的其他文件夹，也就是说并没有只下载特定文件夹。看起来整个项目的文件都在里面。

**Comment by Momo707577045** [comment]
感谢反馈，我修复好再回复您

**Comment by Momo707577045** [comment]
问题已修复，再次感谢你的反馈
