### ISSUE TITLE
对这个在线下载工具支持下载的文件地址格式有疑问，具体内容见正文

### ISSUE THREAD

**Issue by P3R5T7U9** [Momo707577045/github-directory-downloader#5]
Mo大你开发的这个在线下载工具是不支持下载位于仓库根目录下的单个文件或位于多层子文件夹下的单个文件么？？
比如今天我想用这个工具来下载以下两个shell脚本：
https://github.com/SetoSkins/Old_SetoThermal/blob/main/install.sh
https://github.com/SetoSkins/Old_SetoThermal/blob/main/mods/01_8100/files/service.sh
##
最开始输入想要下载的文件地址后，点击解析，没过几秒，直接弹出“链接不正确，请查看链接是否有效”的报错窗口，将相应问题已录制成动图，将其上传到图床上了，但issue里外图床外链没有自动播放，可能体积过大，只好将外链贴上，如下：
https://ibb.co/8PnW736
##
随后我考虑可能因为Github在国内网络特殊原因，挂上v2ray，连上节点后，重新下载，这次却显示下载文件发生错误，换了好几个节点测试下载情况，还是显示下载文件发生错误，如上所述，动图体积可能过大，导致无法自动播放，将相应问题的图床外链贴上，如下：
https://ibb.co/DGcvSWh
##
上述的两种报错情况，都是在排除浏览器兼容性问题的前提下测试，所以不知这个在线下载工具是不支持下载类似“仓库名/blob/main/file”这种链接的单文件么？？看之前站友反馈的问题，都是基于类似“仓库名/tree/各分支/file”这种格式的下载链接来反馈😖

**Comment by Momo707577045** [comment]
感谢回复，我抽空修复下

**Comment by Momo707577045** [comment]
问题修复啦，非常感谢你的反馈，反馈很细致，很用心，点赞
